### ISSUE TITLE
dataHPPC

### ISSUE THREAD

**Issue by Shiv99199** [kmtran95/Battery-HPPC-model-fitting#1]
Hi,

Can you please add the dataHPPC file? It only works when the data file is there.

Thank you,
Shiv

**Comment by kmtran95** [comment]
The dataHPPC file is the actual dataset of the HPPC run. You can perform the HPPC runs yourself and apply the data to these codes, or if you don't have the data, you can contact the authors from https://doi.org/10.3390/batteries7030051. Thanks!
