### ISSUE TITLE
Is there any relevant data to test. I try to substitute my own data. The code always makes mistakes. It would be great if I could run through one data. If you can share, you can send an email 617143376@qq.com Thank you very much for this

### ISSUE THREAD

**Issue by shenshenbore** [kmtran95/Battery-HPPC-model-fitting#2]

**Comment by shenshenbore** [comment]
Is there any relevant data to test. I try to substitute my own data. The code always makes mistakes. It would be great if I could run through one data. If you can share, you can send an email 617143376@qq.com Thank you very much for it

**Comment by kmtran95** [comment]
I sent you an email
